// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CitySelect: typeof import('./components/city-select/city-select.vue')['default']
    Collapse: typeof import('./components/Collapse/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shopping: typeof import('./components/Shopping/index.vue')['default']
  }
}
